
spring:
  datasource:
    druid:
      url: jdbc:mysql://192.168.1.164:3306/zjdatabase?autoreconnect = true&useUnicode=true
      username: root
      password: 123456
      driver-class-name: com.mysql.cj.jdbc.Driver
      max-active: 20
  application:
    name: taskmanager

#  jackson:
#    time-zone: GMT+8
#    date-format: yyyy-MM-dd HH:mm:ss
server:
  port:  8889
eureka:
  client:
    service-url:
#      defaultZone: http://192.168.1.171:8761/eureka

       defaultZone: http://localhost:8085/eureka
mybatis:
  # spring boot集成mybatis的方式打印sql
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

logging:
  level:
    com.eth.wallet.mapper: debug

